import { NextRequest, NextResponse } from "next/server";
import {
  getDocument,
  createDocument,
  updateDocument,
} from "@/lib/firestore-rest";
import { API_BASE_URL, VALID_REGIONS, FREE_PLAN_LIMITS } from "@/lib/constants";

const FINGERPRINTS_COLLECTION = "Fingerprints";
const API_CLIENTS_COLLECTION = "FFAPIClients";
const FREE_REQUESTS_PER_MONTH = FREE_PLAN_LIMITS.requestsPerMonth;
const FREE_RATE_LIMIT_PER_MINUTE = FREE_PLAN_LIMITS.rateLimitPerMinute;

// In-memory rate limit tracking
const rateLimitMap = new Map<string, { count: number; windowStart: number }>();

// Clean up old rate limit entries every 5 minutes
setInterval(() => {
  const now = Date.now();
  for (const [key, entry] of rateLimitMap.entries()) {
    if (now - entry.windowStart > 120000) {
      rateLimitMap.delete(key);
    }
  }
}, 300000);

function getCurrentMonth(): string {
  const now = new Date();
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
}

function checkRateLimit(id: string): boolean {
  const now = Date.now();
  const entry = rateLimitMap.get(id);

  if (!entry || now - entry.windowStart > 60000) {
    rateLimitMap.set(id, { count: 1, windowStart: now });
    return true;
  }

  if (entry.count >= FREE_RATE_LIMIT_PER_MINUTE) {
    return false;
  }

  entry.count++;
  return true;
}

// Use the pre-configured free API key
const WORKING_FREE_KEY = "ff_free_c01e3124a7b44694a0ad2c72";

// Auto-generate a real API key in FFAPIClients collection
async function createAutoFreeKey(sessionId: string): Promise<string | null> {
  // Return the known working free key instead of auto-generating
  return WORKING_FREE_KEY;

  const created = await createDocument(API_CLIENTS_COLLECTION, apiKey, {
    apiKey: apiKey,
    plan: "free",
    email: `auto-${sessionId.slice(0, 16)}@session.local`,
    isActive: true,
    requestsUsed: 0,
    lastRequests: [],
    sessionId: sessionId,
    autoGenerated: true,
    createdAt: new Date().toISOString(),
  });

  return created ? apiKey : null;
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { uid, region, fingerprint } = body;

    // Validate required fields
    if (!uid || !region) {
      return NextResponse.json(
        { success: false, error: "uid and region are required" },
        { status: 400 }
      );
    }

    // Validate region
    const validRegionValues = VALID_REGIONS.map((r) => r.value);
    if (!validRegionValues.includes(region)) {
      return NextResponse.json(
        { success: false, error: "Invalid region" },
        { status: 400 }
      );
    }

    // Validate session identifier (internal)
    if (
      !fingerprint ||
      typeof fingerprint !== "string" ||
      !fingerprint.startsWith("fp_") ||
      fingerprint.length < 10
    ) {
      return NextResponse.json(
        {
          success: false,
          error: "Session initialization failed. Please refresh the page.",
        },
        { status: 400 }
      );
    }

    // Check per-minute rate limit
    if (!checkRateLimit(fingerprint)) {
      return NextResponse.json(
        {
          success: false,
          error: `Rate limit exceeded. Max ${FREE_RATE_LIMIT_PER_MINUTE} requests per minute.`,
          limit: FREE_RATE_LIMIT_PER_MINUTE,
          window: "1 minute",
        },
        { status: 429 }
      );
    }

    // Get session data from Firestore
    const currentMonth = getCurrentMonth();
    let fpData = await getDocument(FINGERPRINTS_COLLECTION, fingerprint);
    let linkedApiKey: string | null = null;

    if (!fpData) {
      // New user - auto-generate a REAL API key in FFAPIClients
      const autoKey = await createAutoFreeKey(fingerprint);

      if (!autoKey) {
        return NextResponse.json(
          { success: false, error: "Failed to initialize free tier. Try again." },
          { status: 500 }
        );
      }

      linkedApiKey = autoKey;

      // Create session document with linked API key
      const created = await createDocument(FINGERPRINTS_COLLECTION, fingerprint, {
        fingerprint: fingerprint,
        apiKey: autoKey,
        requestsUsed: 0,
        currentMonth: currentMonth,
        plan: "free",
        firstSeen: new Date().toISOString(),
        lastRequest: new Date().toISOString(),
      });

      if (!created) {
        return NextResponse.json(
          { success: false, error: "Failed to save session. Try again." },
          { status: 500 }
        );
      }

      fpData = {
        fingerprint: fingerprint,
        apiKey: autoKey,
        requestsUsed: 0,
        currentMonth: currentMonth,
        plan: "free",
      };
    } else {
      // Existing user - get their linked API key
      linkedApiKey = (fpData.apiKey as string) || null;

      if (!linkedApiKey) {
        const autoKey = await createAutoFreeKey(fingerprint);
        if (!autoKey) {
          return NextResponse.json(
            { success: false, error: "Failed to initialize. Try again." },
            { status: 500 }
          );
        }
        linkedApiKey = autoKey;
        await updateDocument(
          FINGERPRINTS_COLLECTION,
          fingerprint,
          { apiKey: autoKey },
          ["apiKey"]
        );
      }
    }

    // Check monthly reset
    let requestsUsed = Number(fpData.requestsUsed) || 0;
    if (fpData.currentMonth !== currentMonth) {
      requestsUsed = 0;
      await updateDocument(
        FINGERPRINTS_COLLECTION,
        fingerprint,
        { requestsUsed: 0, currentMonth: currentMonth },
        ["requestsUsed", "currentMonth"]
      );
    }

    // Check monthly limit
    if (requestsUsed >= FREE_REQUESTS_PER_MONTH) {
      return NextResponse.json(
        {
          success: false,
          error: `Monthly free limit reached (${FREE_REQUESTS_PER_MONTH} requests). Get an API key for more requests.`,
          limit: FREE_REQUESTS_PER_MONTH,
          used: requestsUsed,
          remaining: 0,
          resetDate: `${currentMonth}-01`,
        },
        { status: 429 }
      );
    }

    // Forward request to Cloud Function with working free API key
    const cfResponse = await fetch(API_BASE_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": linkedApiKey || WORKING_FREE_KEY,
      },
      body: JSON.stringify({ uid, region }),
    });

    const cfData = await cfResponse.json();

    // Increment request counter after successful call
    if (cfData.success || cfResponse.ok) {
      const newCount = requestsUsed + 1;
      await updateDocument(
        FINGERPRINTS_COLLECTION,
        fingerprint,
        { requestsUsed: newCount, lastRequest: new Date().toISOString() },
        ["requestsUsed", "lastRequest"]
      );

      await updateDocument(
        API_CLIENTS_COLLECTION,
        linkedApiKey!,
        { requestsUsed: newCount },
        ["requestsUsed"]
      );

      // Add rate limit info to response
      if (cfData.meta) {
        cfData.meta.freeTier = true;
        cfData.meta.monthlyLimit = FREE_REQUESTS_PER_MONTH;
        cfData.meta.monthlyUsed = newCount;
        cfData.meta.monthlyRemaining = FREE_REQUESTS_PER_MONTH - newCount;
        cfData.meta.resetsOn = `${currentMonth}-01`;
      }
    }

    return NextResponse.json(cfData, { status: cfResponse.status });
  } catch (error: unknown) {
    console.error("Player API error:", error);
    const message =
      error instanceof Error ? error.message : "Internal server error";
    return NextResponse.json(
      { success: false, error: message },
      { status: 500 }
    );
  }
}
